spring:
  application:
    name: knmz-api
  profiles:
    active: dev

data-center-id: 3
server-id: 12

#mybatis-plus:
#  dao-locations: classpath:/dao/*Mapper.xml
#  #实体扫描，多个package用逗号或者分号分隔
#  typeAliasesPackage: io.eventoken.wallet.entity
#  #typeEnumsPackage: com.baomidou.springboot.entity.enums
#  global-config:
#    #刷新mapper 调试神器1
#    db-config:
#      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
#      id-type: AUTO
#      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
#      field-strategy: not_empty
#      #驼峰下划线转换
#      column-underline: true
#      #数据库大写下划线转换
#      #capital-mode: true
#      #逻辑删除配置
#      logic-delete-value: 1
#      logic-not-delete-value: 0
#      db-type: mysql
#    refresh: true
#      #自定义填充策略接口实现
#      #meta-object-handler: com.baomidou.springboot.xxx
#    #自定义SQL注入器
#  #sql-injector: com.baomidou.mybatisplus.extension.injector.LogicSqlInjector
#  configuration:
#    map-underscore-to-camel-case: true
#    cache-enabled: false

mybatis-plus:
  global-config:
    db-config:
      table-underline: true
      capital-mode: true


